# Generated by Django 5.1.4 on 2025-03-05 14:26

import django.db.models.deletion
import taggit.managers
import utilities.json
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('extras', '0122_charfield_null_choices'),
    ]

    operations = [
        migrations.CreateModel(
            name='License',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False)),
                ('created', models.DateTimeField(auto_now_add=True, null=True)),
                ('last_updated', models.DateTimeField(auto_now=True, null=True)),
                ('custom_field_data', models.JSONField(blank=True, default=dict, encoder=utilities.json.CustomFieldJSONEncoder)),
                ('license_key', models.CharField(max_length=255, unique=True)),
                ('software_name', models.CharField(max_length=255)),
                ('description', models.TextField(blank=True, null=True)),
                ('vendor', models.CharField(max_length=255)),
                ('purchase_date', models.DateField()),
                ('expiry_date', models.DateField()),
                ('max_assignments', models.IntegerField(default=1)),
                ('assignment_type', models.CharField(default='DEVICES', max_length=50)),
                ('type', models.CharField(default='SUBSCRIPTION', max_length=50)),
                ('status', models.CharField(default='ACTIVE', max_length=50)),
                ('comment', models.TextField(blank=True, null=True)),
                ('tags', taggit.managers.TaggableManager(through='extras.TaggedItem', to='extras.Tag')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='LicenseAssignment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False)),
                ('created', models.DateTimeField(auto_now_add=True, null=True)),
                ('last_updated', models.DateTimeField(auto_now=True, null=True)),
                ('custom_field_data', models.JSONField(blank=True, default=dict, encoder=utilities.json.CustomFieldJSONEncoder)),
                ('assigned_quantity', models.IntegerField(default=1)),
                ('device_name', models.CharField(blank=True, max_length=255, null=True)),
                ('device_owner', models.CharField(blank=True, max_length=255, null=True)),
                ('serial_number', models.CharField(blank=True, max_length=255, null=True)),
                ('device_type', models.CharField(default='PC', max_length=50)),
                ('status', models.CharField(default='ASSIGNED', max_length=50)),
                ('description', models.TextField(blank=True, null=True)),
                ('ticket_number', models.CharField(blank=True, max_length=100, null=True)),
                ('activation_date', models.DateField(auto_now_add=True)),
                ('comment', models.TextField(blank=True, null=True)),
                ('license', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='assignments', to='license_management.license')),
                ('tags', taggit.managers.TaggableManager(through='extras.TaggedItem', to='extras.Tag')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
