# Generated by Django 5.1.4 on 2025-04-03 09:45

import django.db.models.deletion
import taggit.managers
import utilities.json
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('extras', '0122_charfield_null_choices'),
        ('license_management', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='LicenseModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False)),
                ('created', models.DateTimeField(auto_now_add=True, null=True)),
                ('last_updated', models.DateTimeField(auto_now=True, null=True)),
                ('custom_field_data', models.JSONField(blank=True, default=dict, encoder=utilities.json.CustomFieldJSONEncoder)),
                ('name', models.CharField(max_length=50, unique=True)),
                ('slug', models.SlugField(unique=True)),
                ('tags', taggit.managers.TaggableManager(through='extras.TaggedItem', to='extras.Tag')),
            ],
            options={
                'verbose_name': 'License Model',
                'verbose_name_plural': 'License Models',
            },
        ),
        migrations.AlterField(
            model_name='licensetype',
            name='license_model',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='license_types', to='license_management.licensemodel'),
        ),
    ]
