# Generated by Django 5.1.4 on 2025-03-06 15:32

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dcim', '0200_populate_mac_addresses'),
        ('license_management', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='license',
            name='vendor',
        ),
        migrations.RemoveField(
            model_name='licenseassignment',
            name='activation_date',
        ),
        migrations.RemoveField(
            model_name='licenseassignment',
            name='device_name',
        ),
        migrations.RemoveField(
            model_name='licenseassignment',
            name='device_owner',
        ),
        migrations.RemoveField(
            model_name='licenseassignment',
            name='device_type',
        ),
        migrations.RemoveField(
            model_name='licenseassignment',
            name='serial_number',
        ),
        migrations.AddField(
            model_name='license',
            name='manufacturer',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='licenses', to='dcim.manufacturer'),
        ),
        migrations.AddField(
            model_name='licenseassignment',
            name='assigned_on',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AddField(
            model_name='licenseassignment',
            name='device',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='license_assignments', to='dcim.device'),
        ),
    ]
