# Generated by Django 5.1.4 on 2025-04-10 13:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('license_management', '0002_alter_license_manufacturer_alter_license_tags_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='licensetype',
            name='volume_relation',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
    ]
