# Generated by Django 5.1.4 on 2025-04-03 13:53

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('license_management', '0002_licensemodel_alter_licensetype_license_model'),
    ]

    operations = [
        migrations.AddField(
            model_name='licensetype',
            name='base_license',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='expansions', to='license_management.licensetype'),
        ),
    ]
