# Generated by Django 5.1.4 on 2025-03-13 12:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('license_management', '0002_remove_license_vendor_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='licenseassignment',
            name='comment',
        ),
        migrations.RemoveField(
            model_name='licenseassignment',
            name='description',
        ),
        migrations.RemoveField(
            model_name='licenseassignment',
            name='ticket_number',
        ),
    ]
