# Generated by Django 5.1.6 on 2025-04-25 11:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('license_management', '0003_licensetype_volume_relation'),
    ]

    operations = [
        migrations.AlterField(
            model_name='licensetype',
            name='license_model',
            field=models.CharField(default='base', max_length=20),
        ),
    ]
