# Generated by Django 5.1.6 on 2025-03-14 10:43

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('license_management', '0003_remove_licenseassignment_comment_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='license',
            old_name='max_assignments',
            new_name='volume_limit',
        ),
        migrations.RenameField(
            model_name='licenseassignment',
            old_name='assigned_on',
            new_name='assigned_to',
        ),
        migrations.RenameField(
            model_name='licenseassignment',
            old_name='assigned_quantity',
            new_name='volume',
        ),
        migrations.RemoveField(
            model_name='license',
            name='comment',
        ),
        migrations.RemoveField(
            model_name='license',
            name='status',
        ),
        migrations.RemoveField(
            model_name='license',
            name='type',
        ),
        migrations.RemoveField(
            model_name='licenseassignment',
            name='status',
        ),
        migrations.AddField(
            model_name='license',
            name='parent_license',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='sub_licenses', to='license_management.license'),
        ),
        migrations.AddField(
            model_name='license',
            name='product_key',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='licenseassignment',
            name='assignment_type',
            field=models.CharField(default='SINGLE', max_length=20),
        ),
        migrations.AddField(
            model_name='licenseassignment',
            name='description',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='license',
            name='assignment_type',
            field=models.CharField(default='SINGLE', max_length=20),
        ),
    ]
