# Generated by Django 5.1.6 on 2025-03-14 11:22

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dcim', '0200_populate_mac_addresses'),
        ('license_management', '0004_rename_max_assignments_license_volume_limit_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='licenseassignment',
            name='assignment_type',
        ),
        migrations.AddField(
            model_name='license',
            name='serial_number',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='licenseassignment',
            name='manufacturer',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='license_assignments', to='dcim.manufacturer'),
        ),
        migrations.AlterField(
            model_name='license',
            name='description',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='license',
            name='volume_limit',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='licenseassignment',
            name='description',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='licenseassignment',
            name='volume',
            field=models.PositiveIntegerField(default=1),
        ),
    ]
