# Generated by Django 5.1.6 on 2025-03-14 11:24

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dcim', '0200_populate_mac_addresses'),
        ('license_management', '0005_remove_licenseassignment_assignment_type_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='licenseassignment',
            name='device',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='license_assignments', to='dcim.device'),
        ),
    ]
