# Generated by Django 5.1.4 on 2025-03-19 13:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('license_management', '0008_license_comments_licenseassignment_comments'),
    ]

    operations = [
        migrations.RenameField(
            model_name='license',
            old_name='assignment_type',
            new_name='volume_type',
        ),
        migrations.AlterField(
            model_name='license',
            name='expiry_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='license',
            name='purchase_date',
            field=models.DateField(blank=True, null=True),
        ),
    ]
