# Generated by Django 5.1.6 on 2025-03-24 13:46

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dcim', '0200_populate_mac_addresses'),
        ('license_management', '0010_licenseassignment_virtual_machine_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='licenseassignment',
            name='device_manufacturer',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='device_license_assignments', to='dcim.manufacturer'),
        ),
    ]
