# Generated by Django 5.1.6 on 2025-03-24 14:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('license_management', '0011_licenseassignment_device_manufacturer'),
    ]

    operations = [
        migrations.RenameField(
            model_name='license',
            old_name='manufacturer',
            new_name='license_manufacturer',
        ),
        migrations.RenameField(
            model_name='licenseassignment',
            old_name='manufacturer',
            new_name='license_manufacturer',
        ),
    ]
