# Generated by Django 5.1.6 on 2025-03-24 16:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('license_management', '0012_rename_manufacturer_license_license_manufacturer_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='license',
            old_name='license_manufacturer',
            new_name='manufacturer',
        ),
        migrations.RenameField(
            model_name='licenseassignment',
            old_name='license_manufacturer',
            new_name='manufacturer',
        ),
    ]
