# Generated by Django 5.1.6 on 2025-03-26 17:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('license_management', '0013_rename_license_manufacturer_license_manufacturer_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='license',
            name='comments',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='licenseassignment',
            name='comments',
            field=models.TextField(blank=True, null=True),
        ),
    ]
