# Generated by Django 5.1.6 on 2025-04-01 09:52

import django.db.models.deletion
import taggit.managers
import utilities.json
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dcim', '0200_populate_mac_addresses'),
        ('extras', '0122_charfield_null_choices'),
        ('license_management', '0014_alter_license_comments_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='license',
            name='name',
        ),
        migrations.RemoveField(
            model_name='license',
            name='product_key',
        ),
        migrations.RemoveField(
            model_name='license',
            name='volume_type',
        ),
        migrations.CreateModel(
            name='LicenseType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False)),
                ('created', models.DateTimeField(auto_now_add=True, null=True)),
                ('last_updated', models.DateTimeField(auto_now=True, null=True)),
                ('custom_field_data', models.JSONField(blank=True, default=dict, encoder=utilities.json.CustomFieldJSONEncoder)),
                ('name', models.CharField(max_length=255)),
                ('slug', models.SlugField(unique=True)),
                ('product_code', models.CharField(blank=True, max_length=255, null=True)),
                ('ean_code', models.CharField(blank=True, max_length=255, null=True)),
                ('volume_type', models.CharField(max_length=20)),
                ('license_model', models.CharField(max_length=20)),
                ('purchase_model', models.CharField(blank=True, max_length=20, null=True)),
                ('description', models.CharField(blank=True, max_length=255, null=True)),
                ('comments', models.TextField(blank=True, null=True)),
                ('manufacturer', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='license_types', to='dcim.manufacturer')),
                ('tags', taggit.managers.TaggableManager(through='extras.TaggedItem', to='extras.Tag')),
            ],
            options={
                'verbose_name': 'License Type',
                'verbose_name_plural': 'License Types',
            },
        ),
        migrations.AddField(
            model_name='license',
            name='license_type',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='licenses', to='license_management.licensetype'),
        ),
    ]
