# Generated by Django 5.1.6 on 2025-04-01 09:54

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('license_management', '0015_remove_license_name_remove_license_product_key_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='license',
            name='license_type',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.PROTECT, related_name='licenses', to='license_management.licensetype'),
            preserve_default=False,
        ),
    ]
