# Generated by Django 5.1.6 on 2025-05-05 11:26

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('netbox_license', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='license',
            name='parent_license',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='sub_licenses', to='netbox_license.license'),
        ),
        migrations.AlterField(
            model_name='licensetype',
            name='base_license',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='expansions', to='netbox_license.licensetype'),
        ),
    ]
