# Generated by Django 5.1.6 on 2025-05-06 10:05

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('netbox_license', '0002_alter_license_parent_license_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='licenseassignment',
            name='license',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='assignments', to='netbox_license.license'),
        ),
    ]
